### PR TITLE
adapt data interface change with L1

### PR DESCRIPTION
**Pull request by Jason-Zhangxin-Chen**
To close https://github.com/autonity/autonity/issues/812, it requires the oracle server side to be aligned with the new interface. 
As oracle-client watches the on-chain prices for debug loggings,  it have to use the `success` code to replaced the legacy status code of price from oracle contract with the PR of https://github.com/autonity/autonity/pull/967.  

Thus, this PR present the adapation with L1 of the data interface update in oracle contract, it also update the local E2E test framework to adapt with the latest protocols of Autonity client.

### CODE REVIEW

**Comment by vpiyush** [comment]
I have reviewed the priceStatus change part, But there seems to be other changes, which i couldn't get the context of. Could you add some info about it

**Comment by Jason-Zhangxin-Chen** [comment]
> I have reviewed the priceStatus change part, But there seems to be other changes, which i couldn't get the context of. Could you add some info about it

I update the description of the PR to let you know the details.

**Comment by Jason-Zhangxin-Chen** [comment]
> I have reviewed the priceStatus change part, But there seems to be other changes, which i couldn't get the context of. Could you add some info about it

The other changes were about the adaptation in the e2e test framework with the mini Autonity Network setups.

**Comment by Jason-Zhangxin-Chen** [comment]
Going to merge this PR since there is just a single status code update in the round data returned from L1 Autonity Oracle Contract, the other changes are about the e2e test framework update.

**Pull request merged**
