### PR TITLE
config, add missing symbol NTN-ATN to client and the simulator.

### PR DESCRIPTION
**Pull request by Jason-Zhangxin-Chen**
Add the missing symbol as one of the default symbols in oracle client, and add it in the data simulator as well.

### CODE REVIEW

**Review by aiman — COMMENTED** [review]
LGTM

**Review by raj-shekhar1 — APPROVED** [review]

**Review by cmjc — APPROVED** [review]
This lgtm.

**Review by cmjc — CHANGES_REQUESTED** [review]
@Jason-Zhangxin-Chen I have found an error in file data_source_simulator/README.md 

The old URI for the simulator feed is given in section:

>### Query symbol prices
>Same API spec as Binance API spec for the handler of "/api/v3/ticker/price", the query string contains parameter symbols
and its value which is a JSON list of string of symbol name.
>    curl -X 'GET' 'http://127.0.0.1:50991/api/v3/ticker/price?symbols=%5B%22NTN-USD%22%2C%22ATN-USD%22%5D' -H 'accept: application/json'

The new URI is https://simfeed.bakerloo.autonity.org/api/v3/ticker/price

i.e. the curl should be:

curl -X 'GET' 'https://simfeed.bakerloo.autonity.org/api/v3/ticker/price?symbols=%5B%22NTN-USD%22%2C%22ATN-USD%22%5D' -H 'accept: application/json'

**Comment by Jason-Zhangxin-Chen** [comment]
> @Jason-Zhangxin-Chen I have found an error in file data_source_simulator/README.md
> 
> The old URI for the simulator feed is given in section:
> 
> > ### Query symbol prices
> > Same API spec as Binance API spec for the handler of "/api/v3/ticker/price", the query string contains parameter symbols
> > and its value which is a JSON list of string of symbol name.
> > curl -X 'GET' 'http://127.0.0.1:50991/api/v3/ticker/price?symbols=%5B%22NTN-USD%22%2C%22ATN-USD%22%5D' -H 'accept: application/json'
> 
> The new URI is https://simfeed.bakerloo.autonity.org/api/v3/ticker/price
> 
> i.e. the curl should be:
> 
> curl -X 'GET' 'https://simfeed.bakerloo.autonity.org/api/v3/ticker/price?symbols=%5B%22NTN-USD%22%2C%22ATN-USD%22%5D' -H 'accept: application/json'

resolved in 861fc91c7d5f154a364b9ecb7ac0f8a480c32d98

**Review by cmjc — APPROVED** [review]
👍

**Pull request merged**
